import WorkoutSessionFlow from "@/components/workouts/WorkoutSessionFlow";

const espaldaBicepsPlan = {
  title: "Espalda + Bíceps",
  exercises: [
    {
      name: "Jalón al pecho",
      objective: "Más tracción.",
      weight: 45,
      sets: 4,
      reps: "8 - 10",
      repsCompleted: 10,
      rir: "2",
      tempo: "3-1-1",
      restSeconds: 120,
      coach: "Lleva la barra hasta la parte alta del pecho sin balancear el torso.",
      muscles: { primary: "Dorsal ancho", secondary: "Bíceps, redondo mayor" },
      alternatives: ["Dominadas asistidas", "Jalón neutro"],
      anatomyNote:
        "Este ejercicio abre la sesión porque permite activar el dorsal ancho con una curva de aprendizaje sencilla y buena estabilidad, antes de pasar a otros ángulos de tracción más exigentes técnicamente.",
      technique: {
        title: "Jalón al pecho con técnica limpia",
        steps: [
          "Ajusta el soporte de rodillas para que queden firmes.",
          "Toma la barra con un agarre un poco más ancho que los hombros.",
          "Inclina el torso ligeramente hacia atrás sin arquear la espalda baja.",
          "Lleva la barra hacia la parte alta del pecho controlando el recorrido.",
          "Sube el peso extendiendo los brazos sin bloquear los codos con fuerza.",
        ],
        mistakes: [
          "Balancear el torso para generar impulso.",
          "Tirar la barra detrás de la nuca.",
          "Usar solo los brazos sin activar la espalda.",
          "Soltar el peso de golpe en la fase de subida.",
        ],
        cues: [
          "Pecho elevado, hombros hacia atrás",
          "Agarre firme y uniforme",
          "Espalda controla el movimiento, no los brazos",
          "Sube el peso sin bloquear los codos",
        ],
      },
    },
    {
      name: "Jalón agarre cerrado (triángulo)",
      objective: "Más contracción dorsal.",
      weight: 35,
      sets: 3,
      reps: "10 - 12",
      repsCompleted: 12,
      rir: "1 - 2",
      tempo: "2-1-2",
      restSeconds: 90,
      coach: "Lleva el triángulo hacia la parte alta del pecho manteniendo los codos cerca del cuerpo.",
      muscles: { primary: "Dorsal ancho", secondary: "Bíceps, dorsal medio" },
      alternatives: ["Jalón unilateral", "Jalón neutro"],
    },
    {
      name: "Remo sentado en máquina",
      objective: "Más densidad.",
      weight: 40,
      sets: 4,
      reps: "8 - 10",
      repsCompleted: 10,
      rir: "2",
      tempo: "2-1-2",
      restSeconds: 120,
      coach: "Máquina convergente: puedes trabajar ambos brazos a la vez o de forma unilateral. Junta los omóplatos al final del recorrido sin usar impulso de cadera.",
      muscles: { primary: "Dorsal medio", secondary: "Romboides, bíceps" },
      alternatives: ["Remo con mancuerna", "Remo en polea baja", "Remo con barra T"],
    },
    {
      name: "Pullover en polea",
      objective: "Más estiramiento dorsal.",
      weight: 20,
      sets: 3,
      reps: "12 - 15",
      repsCompleted: 12,
      rir: "1 - 2",
      tempo: "2-1-2",
      restSeconds: 90,
      coach: "Estira bien arriba sin perder la tensión en el dorsal.",
      muscles: { primary: "Dorsal ancho", secondary: "Serrato" },
      alternatives: ["Pullover con mancuerna"],
    },
    {
      name: "Curl predicador",
      objective: "Más aislamiento.",
      weight: 14,
      sets: 3,
      reps: "10 - 12",
      repsCompleted: 12,
      rir: "1 - 2",
      tempo: "2-1-2",
      restSeconds: 75,
      coach: "Extiende completo sin bloquear el codo con fuerza.",
      muscles: { primary: "Bíceps braquial", secondary: "—" },
      alternatives: ["Scott con barra EZ"],
    },
    {
      name: "Curl martillo",
      objective: "Cerrar con precisión.",
      weight: 12,
      sets: 3,
      reps: "10 - 12",
      repsCompleted: 10,
      rir: "1 - 2",
      tempo: "2-1-2",
      restSeconds: 75,
      coach: "Mantén la muñeca neutra durante todo el recorrido.",
      muscles: { primary: "Bíceps", secondary: "Braquial, antebrazo" },
      alternatives: ["Martillo en cuerda"],
    },
  ],
};

export default function ExercisePage() {
  return <WorkoutSessionFlow plan={espaldaBicepsPlan} />;
}
